In [1]:
import json
import yfinance as yf

In [2]:
tickers = json.load(open('tickers.json'))

In [3]:
df = yf.download(tickers, start='2021-01-01')
df = df['Close']
df

[*********************100%%**********************]  23 of 23 completed

Ticker,AAPL,AMZN,BRK-A,BTC-USD,BYDDF,CL=F,COIN,CSPX.AS,ETH-USD,GC=F,...,META,MSFT,MSTR,NVDA,PYPL,SI=F,SOL-USD,TSLA,UA,VAPU.SW
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-01,NaN,NaN,NaN,29374.152344,NaN,NaN,NaN,NaN,730.367554,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.842084,NaN,NaN,NaN
2021-01-02,NaN,NaN,NaN,32127.267578,NaN,NaN,NaN,NaN,774.534973,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.799275,NaN,NaN,NaN
2021-01-03,NaN,NaN,NaN,32782.023438,NaN,NaN,NaN,NaN,975.507690,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.161752,NaN,NaN,NaN
2021-01-04,129.410004,159.331497,343525.0,31971.914062,28.049999,47.619999,NaN,304.475006,1040.233032,1944.699951,...,268.940002,217.690002,425.220001,13.113500,231.919998,27.284000,2.485097,243.256668,15.06,32.166698
2021-01-05,131.009995,160.925507,341820.0,33992.429688,29.950001,49.930000,NaN,304.990997,1100.006104,1952.699951,...,270.970001,217.899994,428.630005,13.404750,234.910004,27.570999,2.157217,245.036667,15.45,32.446800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-03,NaN,NaN,NaN,60680.093750,NaN,NaN,NaN,NaN,2903.385742,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,142.921997,NaN,NaN,NaN
2024-08-04,NaN,NaN,NaN,58116.976562,NaN,NaN,NaN,NaN,2686.398926,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,138.055084,NaN,NaN,NaN
2024-08-05,209.270004,161.020004,620040.0,53991.457031,27.309999,72.940002,189.470001,502.354004,2417.206299,2401.699951,...,475.730011,395.149994,1309.000000,100.449997,60.459999,27.076000,129.864304,198.880005,6.18,24.785000
2024-08-06,207.229996,161.929993,633175.0,56034.316406,27.040001,73.199997,194.169998,507.924988,2458.723877,2389.100098,...,494.089996,399.609985,1369.209961,104.250000,62.750000,27.096001,144.090363,200.639999,6.30,25.010000
2024-08-07,NaN,NaN,NaN,56990.687500,NaN,74.889999,NaN,511.703003,2469.782227,2442.500000,...,NaN,NaN,NaN,NaN,NaN,27.205000,151.795151,NaN,NaN,NaN

In [4]:
df.to_csv('raw_data.csv')