In [1]:
import pandas as pd
import yfinance as yf

In [2]:
tickers = pd.read_csv('data/tickers.csv')
tickers = tickers['tickers'].tolist()

In [3]:
df = yf.download(tickers, start='2021-01-01')
df = df['Close']
df

[*********************100%%**********************]  23 of 23 completed

Ticker,AAPL,AMZN,BRK-A,BTC-USD,BYDDF,CL=F,COIN,CSPX.AS,ETH-USD,GC=F,...,META,MSFT,MSTR,NVDA,PYPL,SI=F,SOL-USD,TSLA,UA,VAPU.SW
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-01,NaN,NaN,NaN,29374.152344,NaN,NaN,NaN,NaN,730.367554,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.842084,NaN,NaN,NaN
2021-01-02,NaN,NaN,NaN,32127.267578,NaN,NaN,NaN,NaN,774.534973,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.799275,NaN,NaN,NaN
2021-01-03,NaN,NaN,NaN,32782.023438,NaN,NaN,NaN,NaN,975.507690,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.161752,NaN,NaN,NaN
2021-01-04,129.410004,159.331497,343525.0,31971.914062,28.049999,47.619999,NaN,304.475006,1040.233032,1944.699951,...,268.940002,217.690002,42.521999,13.113500,231.919998,27.284000,2.485097,243.256668,15.06,32.166698
2021-01-05,131.009995,160.925507,341820.0,33992.429688,29.950001,49.930000,NaN,304.990997,1100.006104,1952.699951,...,270.970001,217.899994,42.862999,13.404750,234.910004,27.570999,2.157217,245.036667,15.45,32.446800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,209.270004,161.020004,620040.0,53991.457031,27.309999,72.940002,189.470001,502.354004,2417.206299,2401.699951,...,475.730011,395.149994,130.899994,100.449997,60.459999,27.076000,129.864304,198.880005,6.18,24.785000
2024-08-06,207.229996,161.929993,633175.0,56034.316406,27.040001,73.199997,194.169998,507.924988,2458.723877,2389.100098,...,494.089996,399.609985,136.921005,104.250000,62.750000,27.096001,144.090363,200.639999,6.30,25.010000
2024-08-07,209.820007,162.770004,641000.0,55027.460938,26.900000,75.230003,178.910004,513.155029,2336.589355,2390.500000,...,488.920013,398.429993,124.684998,98.910004,62.740002,26.830000,144.632095,191.759995,6.27,25.895000
2024-08-08,213.309998,165.800003,648888.0,61710.136719,27.000000,76.190002,192.320007,512.713013,2683.352783,2422.199951,...,509.630005,402.690002,135.990005,104.970001,64.279999,27.500000,162.930740,198.839996,7.42,25.469999
2024-08-09,NaN,NaN,NaN,60854.363281,NaN,76.169998,NaN,NaN,2682.854492,2458.000000,...,NaN,NaN,NaN,NaN,NaN,27.530001,156.650497,NaN,NaN,NaN

In [4]:
df.to_csv('data/raw_data.csv')